name: Build and Push Docker Container to Azure Container Registry 

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:        
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Gets semantic release info
      id: semantic_release_info
      uses: jossef/action-semantic-release-info@v1
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN_UPDATE_VERSION }}

    - name: Update appsettings.json version
      uses: jossef/action-set-json-field@v1
      with:
        file: src/Teams.Web/appsettings.json
        field: Version
        value: ${{ steps.semantic_release_info.outputs.git_tag }}
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *
        git commit -m "bumping release ${{ steps.semantic_release_info.outputs.git_tag }}"
        git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.SECRET_TOKEN_UPDATE_VERSION }}
        tags: true
    
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_NAME }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    - name: Build and Push container to ACR
      run: |
        cd src
        docker-compose build
        docker image tag teams:latest ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
        docker image push ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
        
