name: Build and Push Docker Container to Azure Container Registry 

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:        
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update appsettings.json version
      uses: jossef/action-set-json-field@v1
      with:
        file: src/Teams.Web/appsettings.json
        field: Version
        value: "1.0.${{ github.run_number }}"
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add *
        git commit -m "update version ${{ github.run_id }}"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.SECRET_TOKEN_UPDATE_VERSION }}
    
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_NAME }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    - name: Build and Push container to ACR
      run: |
        cd src
        docker-compose build
        docker image tag teams:latest ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
        docker image push ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
        
