name: Build and Push Docker Container to Azure Container Registry 

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    
    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY_NAME }}
        username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and Push container to ACR
      run: |
        cd src
        docker-compose build
        docker image tag teams:latest ${{ secrets.CONTAINER_REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:latest
        docker image push ${{ secrets.CONTAINER_REGISTRY_NAME }}:latest
        
